networks:
  app-network-public:
    driver: bridge

# volumes:
#   sql-server-data:
#     driver: local
#   sqldata:
#   sqllog:
#   sqlbackup:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-sqlserver
    networks:
      - app-network-public
    restart: always
    env_file:
      - .env
    ports:
      - '1433:1433'
    volumes:
      - /srv/sqlserver/data:/var/opt/mssql/data
      - /srv/sqlserver/log:/var/opt/mssql/log
      - /srv/sqlserver/backup:/var/opt/mssql/backup
      - /srv/sqlserver/secrets:/var/opt/mssql/secrets
      - /srv/shared:/usr/shared