networks:
  app-network-public:
    driver: bridge

# volumes:
#   sql-server-data:
#     driver: local
#   sqldata:
#   sqllog:
#   sqlbackup:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-sqlserver
    networks:
      - app-network-public
    restart: always
    env_file:
      - .env
    ports:
      - '1433:1433'
    volumes:
      - /srv/sqlserver:/var/opt/mssql
      - /srv/shared:/usr/shared