networks:
  app-network-public:
    driver: bridge

# volumes:
#   sql-server-data:
#     driver: local
#   sqldata:
#   sqllog:
#   sqlbackup:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-sqlserver
    networks:
      - app-network-public
    restart: always
    env_file:
      - sqlserver.env
      - sapassword.env
    ports:
      - '1433:1433'
    volumes:
      - ${HOME}/docker/sqlserver/data:/var/opt/sqlserver/data
      # - sqldata:/var/opt/sqlserver/data
      - ${HOME}/docker/sqlserver/log:/var/opt/sqlserver/log
      - ${HOME}/docker/sqlserver/backup:/var/opt/sqlserver/backup
      - ${HOME}/docker/shared:/usr/shared